version: "3"
networks:
  dtables-network:
    driver: bridge
services:
  app:
    image: dtables-www
    environment:
      - APP_ENV=${APP_ENV}
    container_name: dtables-www
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    ports:
      - 8084:80
    networks:
      - dtables-network
  mysql:
    image: mysql:5.7
    container_name: dtables-mysql
    volumes:
      - mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 13307:3306
    environment:
      MYSQL_DATABASE: dtables
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: dtables_user
      MYSQL_PASSWORD: dtables_password
    networks:
      - dtables-network
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: dtables-phpmyadmin
    ports:
      - "8004:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
    depends_on:
      - mysql
    networks:
      - dtables-network
volumes:
  mysql:
    driver: "local"


